apiVersion: v1
kind: Service
metadata:
  name: hello-service
  annotations:
    consul.hashicorp.com/service-tags: "urlprefix-hello.com"
    consul.hashicorp.com/service-sync: "true"
    consul.hashicorp.com/service-name: "hello"
  labels:
    app: hello
spec:
  selector:
    app: hello
  ports:
  - name: http
    port: 8080
    targetPort: 8080
